[project]
name = "pycde_example"
version = "0.1.0"
description = "A collection of examples showcasing PyCDE and Mini RISC-V implementation."
authors = [
    "Dragon-Git <1762578117@qq.com>",
]

dependencies = [
    "PyYAML",
    "cocotb",
    "pycde",
]

[tool.ruff]
line-length = 120